### ISSUE TITLE
Font-Awesome min.css ??

### ISSUE THREAD

**Issue by FizWork** [Smartik89/SMK-Font-Awesome-PHP-JSON#5]
Hi there,

Please check it again...

`$css_path = 'css/fontawesome-all.min.css';`

**Comment by awps** [comment]
Hi.

The CSS is not included. 
If you want to use the 'reader', you must specify the path to the Font Awesome 4.7 CSS file from **your server**.

The CSS may be in a directory named `css`, `assets` or whatever...

For example, use it like this:
```
$icons = new Awps\FontAwesomeReader( __DIR__ .'/css/font-awesome.css' );
```

This is needed only if you want to read the CSS names from a file, but you probably don't need this and you should use just this class:
```
$icons = new Awps\FontAwesome();
```
